# Generated by Django 5.0.6 on 2024-07-31 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_rename_messages_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
