# Generated by Django 5.0.6 on 2024-08-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0006_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
