# Generated by Django 5.0.6 on 2024-08-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0011_alter_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/message_image')),
            ],
        ),
    ]
