# Generated by Django 5.0.6 on 2024-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0012_pre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
