# Generated by Django 5.0.6 on 2024-08-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0015_message_is_read_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/message_audio'),
        ),
    ]
