# Generated by Django 5.0.6 on 2024-07-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_name_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/commentaire'),
        ),
    ]
