# Generated by Django 5.0.6 on 2024-07-20 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_commentaire_created_commentaire_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='username',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='postId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postss', to='base.posts'),
        ),
    ]
