# Generated by Django 5.0.6 on 2024-07-21 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amis',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amis1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amis',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amis2', to=settings.AUTH_USER_MODEL),
        ),
    ]
