# Generated by Django 5.0.6 on 2024-07-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_amis_user1_alter_amis_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
