# Generated by Django 5.0.6 on 2024-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
